### ISSUE TITLE
Incluir datos de tablas idioma, nivel, valor_nivel_idioma

### ISSUE THREAD

**Issue by AlaskaRising** [udistrital/idiomas_crud#17]
Con el fin de terminar el desarrolo de idiomas_crud, es necesario poblar el nuevo modelo con datos de idiomas para que sean utilizados por equipos de desarrollo que lo requieran en sus diferentes sistemas. Así, se decide tomar los datos de [Planestic](https://github.com/planesticud/idiomas_crud/tree/migrations/database/scripts), que ya tenían al respecto,  y se se adecuan a los cambios del esquema. Por esto, se realizan las siguientes tareas:

- [x] Solicitar los scripts que tiene Planestic sobre idiomas
- [x] Realizar una revisión de estos Scripts 
- [x] Corregir las inconsistencias que aquí se presenten
- [x] Insertar la nueva versión de los scripts en la base de datos ambiente TEST
- [x] Revisión por parte de @mafeave de los datos insertados

**Comment by AlaskaRising** [comment]
Fallo el despliegue debido a que una variable no esta actualizada y no encuentra el schema pero la data queda insertada en ambiente Test, para su revisión. 

![image](https://user-images.githubusercontent.com/47569218/70556574-2ed07080-1b4f-11ea-82af-2c1d824739bb.png)

**Comment by mafeave** [comment]
Se verifica la carga de información de idioma, nivel, valor_nivel_idioma del API de idiomas
