### ISSUE TITLE
realizar ajustes sobre la rama feature/integracion master para desplegar en rama propia de planestic

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/idiomas_crud#21]
se requiere realizar los ajustes ya socializados para que los pasos de drone se ejecuten exitosamente, pero en este caso se usara [la plantilla de drone para la rama personalizada de planestic](https://github.com/udistrital/financiera_documentacion/issues/210) .

adicionalmente se requiere eliminar la carpeta `.scannerwork`

**Comment by miguerpe** [comment]
@BOTOOM @jevilla94 @planesticud 

Se realizan los ajustes requeridos
