### ISSUE TITLE
Agregar tablas relacionadas a idiomas a nuevo esquema de base de datos.

### ISSUE THREAD

**Issue by mariaortiz0401** [udistrital/idiomas_crud#3]
Debido a los cambios a nivel de base de datos, es necesario realizar unos ajustes sobre este API para su correcto funcionamiento con la nueva base de datos udistrital_core y los nuevos procesos de migración definidos por la OAS.

Para esto, se definen las siguientes tareas:

- [x]  Crear SQL de creación de esquema y tablas de idiomas
- [x]  Crear archivos de beego migrate. 
- [x]  Revisión por parte de DBA de los scripts.
- [x]  Crear controlador y modelo de tabla aprobado en API
- [x]  Desplegar cambios en el 254
- [x]  Desplegar cambios en test

**Comment by AlaskaRising** [comment]
Se inicia la creación de archivo SQl para esquema idiomas_crud teniendo en cuenta que ya no estarán relacionados a ente u organizaciones si no a el esquema de terceros, se suben cambios a rama dev.

**Comment by nodier25** [comment]
Buen día

Se revisa el modelo y se aprueba para el core

Muchas gracias

**Comment by corio27** [comment]
aprobado

**Comment by AlaskaRising** [comment]
Junto a @mariaalejandra9404 
Se registran variables con equipo de DBA's para despliegue en test queda pendiente corrección de usuario de bases de datos ya que en el despliegue falla en el momento de ejecutar los archivos migrate.

**Comment by mariaortiz0401** [comment]
Se realiza despliegue en TEST y aparece existoso. Esto permitió que se creará el esquema idiomas y las tablas pertenecientes a él. Sin embargo, el API aún no se despliega por problemas en AWS.

**Comment by mariaortiz0401** [comment]
Después de muchas correcciones y de no saber bien qué se hizo, se pudo desplegar API en test:

http://pruebasapi.intranetoas.udistrital.edu.co:8098/v1/idioma

Teoría: Se volvió a una versión pasada del API y tal vez esa versión del entrypoint y el drone.yml permitieron el correcto despliegue. :raised_hands:
